version: '3.7'

services:
  http:
    container_name: sat_http
    image: nginx:latest
    restart: always
    ports:
      - "8008:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/local/http/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/local/http/log:/var/log/nginx
    networks:
      - sat_network

  app:
    container_name: sat
    image: marcelofabianov/php8.2-fpm-dbs:latest
    restart: always
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=app"
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - .:/var/www/html
      - ./docker/local/php/app/php.ini:/usr/local/etc/php/php.ini
    networks:
      - sat_network
    depends_on:
      - app_db
      - redis
    ports:
      - '9009:9000'
      - '9003:9003'

  horizon:
   container_name: sat_horizon_default
   image: marcelofabianov/php8.2-cli-pgsql:latest
   command: php artisan horizon
   restart: always
   working_dir: /var/www/html
   volumes:
     - .:/var/www/html
     - ./docker/local/php/horizon/php.ini:/usr/local/etc/php/php.ini
   networks:
     - sat_network
   depends_on:
     - app_db
     - redis

  schedule:
   container_name: sat_schedule
   image: marcelofabianov/php8.2-cli-pgsql:latest
   command: php artisan schedule:work
   restart: always
   working_dir: /var/www/html
   volumes:
     - .:/var/www/html
     - ./docker/local/php/schedule/php.ini:/usr/local/etc/php/php.ini
   networks:
     - sat_network
   depends_on:
     - app_db
     - redis

  redis:
    container_name: sat_redis
    image: redis:latest
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    volumes:
      - 'sat_redis:/data'
    ports:
      - "4016:6379"
    networks:
      - sat_network

  app_db:
    container_name: sat_app_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: '${DB_USERNAME:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-sat_app_db}'
    volumes:
      - 'sat_app_db:/var/lib/postgresql/data'
    ports:
      - "4015:5432"
    networks:
      - sat_network

networks:
  sat_network:
    driver: bridge

volumes:
  sat_app_db:
    driver: local
  sat_redis:
    driver: local

