version: '3.7'

services:

  app:
    container_name: app
    #build: .
    image: marcelofabianov/php8.2-fpm-oci
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - example_network

networks:
  example_network:
    driver: bridge